spring:
  datasource:
    url: jdbc:mysql://localhost:3306/menu-app?serverTimezone=UTC
    username: root
    password:

  mvc:
    servlet:
      load-on-startup: 1
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

server:
  servlet:
    context-path: /api

app:
  security:
    user-code: my_identifier

logging:
  level:
    lu.perso.menuback: INFO
    org.springframework.data: WARN
